version: '3.5'

services:
  api:
    build: src/InterviewApp.API
    ports:
      - 80:80
    depends_on:
      - db
      - seq
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secretPassword
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
volumes:
  postgres-db:
    driver: local